### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by rgt002** [ejektaflex/Kambrik#23]
Keep getting this crash on startup, the weird thing is that it worked fine the last time I played, then I get on without changing anything and I get this crash.
MC 1.19.2
Fabric 0.14.22

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'kambrik'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of kotlin.jvm.internal.Intrinsics failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.kt)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [jobsaddon.mixins.json:compat.ChopResultMixin from mod jobsaddon] from phase [DEFAULT] in config [jobsaddon.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: ht.treechop.common.chop.ChopResult is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@48ccbb32
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 18 more

**Comment by ejektaflex** [comment]
You haven't provided me your whole log, but it seems like you might not have Fabric Language Kotlin installed.

**Comment by rgt002** [comment]
> You haven't provided me your whole log, but it seems like you might not have Fabric Language Kotlin installed.

It's not the log, it's a crash error that pops up.
![image](https://github.com/ejektaflex/Kambrik/assets/69377192/4e2dfff7-f962-4790-93bf-480a6e9ac4c1)

Here is the console log: https://paste.atlauncher.com/view/8223bab5-574b-4245-a26e-0ea525e86ce3

I do have Fabric Language Kotlin, but ATLauncher is weird. I get most mods from Modrinth, including Fabric Language Kotlin which I also needed for another mod, but Kambrik for 1.19.2 is only available on Curseforge and it seems the launcher doesn't always recognize mods/dependencies from differing websites.

**Comment by ejektaflex** [comment]
If you look at the nested error there, Kambrik's prelaunch entrypoint failed because a mixin injection failed, and that mixin is `ht.treechop.common.chop.ChopResult`, which is from HT's TreeChop mod, not Kambrik.

You should report this on their error tracker.

**Comment by rgt002** [comment]
I will open an issue on their tracker, but it's strange that it would do this out of the blue, it worked the last time I played the instance. Any idea why a mod would randomly throw an error?

**Comment by ejektaflex** [comment]
None of those errors seemed random, unless you updated a mod recently! 
Since this isn't related to Kambrik, I'll be closing it :)
