### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Breach5254** [ejektaflex/Kambrik#24]
While I do have over 300 mods, Ive narrowed down the issue being something to do with Kambrik. I have no idea how to read crash reports fully yet, and need help breaking down where the problem is, and how I could fix it. I am realtively new to modding, so treating me like Im dumb is fine.

Crash report:
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2960 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30)
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: java.lang.ClassCastException: class com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair cannot be cast to class org.apache.commons.lang3.tuple.Pair (com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair and org.apache.commons.lang3.tuple.Pair are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52aa2946)
	at ca.fxco.memoryleakfix.config.mixinExtension.UnMixinExtension.preApply(UnMixinExtension.java:23)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.preApply(Extensions.java:156)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.preApply(TargetClassContext.java:413)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:401)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

Crash log: 
[latest.log](https://github.com/ejektaflex/Kambrik/files/12851714/latest.log)

**Comment by Breach5254** [comment]
Nevermind, I found a new problem when screwing with it. Im going to move to a different repo

**Comment by ejektaflex** [comment]
This is because Kambrik has a prelaunch stage and thus Kambrik's prelaunch startup is interrupted by another mod's mixin failure. It looks like whatever mod isassociated with the package `ca.fxco.memoryleakfix` is failing to inject a mixin.
